### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by Whitehachi** [leoFitz1024/wallhaven#57]
我尝试在Linux上编译，

运行可执行文件报错

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open 'user32.dll.so'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at readFileSync (node:fs:453:35)
    at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at new DynamicLibrary (/media/mahiro/disk5/wallhaven/wallhaven/dist_electron/linux-unpacked/resources/app.asar/node_modules/ffi-napi/lib/dynamic_library.js:68:23)
    at Object.Library (/media/mahiro/disk5/wallhaven/wallhaven/dist_electron/linux-unpacked/resources/app.asar/node_modules/ffi-napi/lib/library.js:47:10)
    at Object.<anonymous> (/media/mahiro/disk5/wallhaven/wallhaven/dist_electron/linux-unpacked/resources/app.asar/electron/wallhaven.js:13:20)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
``` 

难道是没有适配Linux？

**Comment by Whitehachi** [comment]
我尝试了注释了部分代码，编译通过了，软件成功打开
注释的函数：
doChangeBg()
